---
- name: Database server
  hosts: database_server
  roles:
  - common
  - mariadb
  - wordpress
  
- name: Web servers
  hosts: web_servers
  serial: 1
  roles:
  - common
  - apache2
  - postfix
 # - proftpd
  - filestorage
  - wordpress

